### ISSUE TITLE
GitHub app uninstall event

### ISSUE THREAD

**Issue by PRMerger10** [MicrosoftDocs/CSIDev-Public#462]
### :warning: The Git Automator app has been uninstalled on this repo.
Please click [here](https://github.com/apps/integrationtest-checks/installations/231842) to reinstall.

**Comment by PRMerger6** [comment]
@v-caxian @TinaLiuGirl

The Git Automator for PR app has been uninstalled to this repo, which will cause the Git Automator service to be unavailable. Please install it in time, thank you!

**Comment by PRMerger6** [comment]
@v-caxian @TinaLiuGirl

The Git Automator for PR app has been uninstalled to this repo, which will cause the Git Automator service to be unavailable. Please install it in time, thank you!

**Comment by PRMerger6** [comment]
@v-caxian @TinaLiuGirl

The Git Automator for PR app has been uninstalled to this repo, which will cause the Git Automator service to be unavailable. Please install it in time, thank you!

**Comment by PRMerger6** [comment]
@v-caxian @TinaLiuGirl

The Git Automator for PR app has been uninstalled to this repo, which will cause the Git Automator service to be unavailable. Please install it in time, thank you!

**Comment by PRMerger6** [comment]
@v-caxian @TinaLiuGirl

The Git Automator for PR app has been uninstalled to this repo, which will cause the Git Automator service to be unavailable. Please install it in time, thank you!

**Comment by PRMerger6** [comment]
@v-caxian @TinaLiuGirl

The Git Automator for PR app has been uninstalled to this repo, which will cause the Git Automator service to be unavailable. Please install it in time, thank you!

**Comment by PRMerger6** [comment]
@v-caxian @TinaLiuGirl

The Git Automator for PR app has been uninstalled to this repo, which will cause the Git Automator service to be unavailable. Please install it in time, thank you!

**Comment by PRMerger6** [comment]
@v-caxian @TinaLiuGirl

The Git Automator for PR app has been uninstalled to this repo, which will cause the Git Automator service to be unavailable. Please install it in time, thank you!

**Comment by PRMerger6** [comment]
@v-caxian @TinaLiuGirl

The Git Automator for PR app has been uninstalled to this repo, which will cause the Git Automator service to be unavailable. Please install it in time, thank you!

**Comment by PRMerger6** [comment]
@v-caxian @TinaLiuGirl

The Git Automator for PR app has been uninstalled to this repo, which will cause the Git Automator service to be unavailable. Please install it in time, thank you!

**Comment by PRMerger6** [comment]
The Git Automator app has been installed to this repo.
