### ISSUE TITLE
PRMerger not installed

### ISSUE THREAD

**Issue by PRMerger18** [MicrosoftDocs/CSIDev-Public#591]
:warning:PRMerger is no longer installed on this repo. If it was uninstalled intentionally, please confirm that in a comment and close this issue. You will not get this warning again.

If PRMerger was uninstalled unintentionally, click [here](https://github.com/apps/integrationtest-pullrequests/installations/238658) to reinstall it (must be a repo admin). The PRMerger team is investigating the cause of accidental uninstallations.

**Comment by PRMerger19** [comment]
PRMerger has been installed on this repo.
